version: '3.8'

services:
  app:
    container_name: document-management-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - library-db
      - cache

  library-db:
    image: postgres:13.1-alpine
    container_name: library-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  cache:
    image: redis:7.0.10
    container_name: redis-cache
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data: